apiVersion: v1
kind: Service 
metadata:
  name : node-app-service
spec: 
  selector:
    app: hello-world
  type: NodePort
  ports: 
  - name: node-service-port
    protocol: TCP
    port: 3000
    targetPort: app-entry-port
  
