apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-app-deployment
  labels:
    app: hello-world
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-world
  template:
    metadata:
      labels:
        app: hello-world
    spec:
      containers:
      - name: node-app-container
        image: racembenrhayem/gl5-tp3-devops-k8s:1.0
        ports:
        - containerPort: 3000
          name: app-entry-port
        resources : 
          requests:
            memory: '128Mi'
            cpu : '500m'
          limits:
            memory: '256Mi'
            cpu: '1000m'

